### ISSUE TITLE
Website header displays incorrectly on high-resolution displays

### ISSUE THREAD

**Issue by pzmarzly** [johannesjo/super-productivity#128]
Current state:

![screenshot of current page](https://user-images.githubusercontent.com/8074163/50739419-53ee8d80-11e0-11e9-9e68-9af2ffd59cec.png)

Suggestion: replace

```css
.intro-img {
transform: translate(0,-50%);
}
```

with

```css
.intro-img {
transform: translate(-50%,-50%);
left: 50%;
}
```

so on large screens the header will be centered, while displaying just like it did before on smaller screens:

![438c58b2-6da3-4822-9212-245d520b0b54](https://user-images.githubusercontent.com/8074163/50739423-64066d00-11e0-11e9-85b2-7e1548d3921d.png)
