### ISSUE TITLE
[Arch] SNAP package - Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by presianbg** [johannesjo/super-productivity#27]
## Your Environment

* Version used: Latest from SNAP
* Operating System and version: Arch with all packages up-to-date
* Desktop Environment: Cinnamon

## Expected Behavior
The application is starting with this error:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
```
And looks like this:

![image](https://user-images.githubusercontent.com/2163486/33124647-652b120a-cf86-11e7-82c7-bb9eeaa826fc.png)

Any advice?

Btw the web app is awesome!

Best Regards,
Presian

**Comment by johannesjo** [comment]
Hello! Thanks for reporting! Here are some suggestions Does `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module` fix your issue (source: https://askubuntu.com/questions/208431/failed-to-load-module-canberra-gtk-module)?

**Comment by presianbg** [comment]
@johannesjo 
Thanks for fast response. Arch Linux has different package names for those libraries:

````
extra/libcanberra 0.30+2+gc0620e4-1 [installed]
    A small and lightweight implementation of the XDG Sound Theme Specification
extra/libcanberra-gstreamer 0.30+2+gc0620e4-1
    GStreamer plugin for libcanberra
extra/libcanberra-pulse 0.30+2+gc0620e4-1 [installed]
    PulseAudio plugin for libcanberra
multilib/lib32-libcanberra 0.30-4 [installed]
    A small and lightweight implementation of the XDG Sound Theme Specification (32-bit)
multilib/lib32-libcanberra-pulse 0.30-4
    PulseAudio plugin for libcanberra (32-bit)
```
Perhaps it's wrong / missing path? Unfortunately I have poor experience with SNAP , actually it's my fist snap package :), so I'm not able to provide any detailed info without further guidance.

**Comment by johannesjo** [comment]
Thank you! That's already pretty helpful. I did a little research. Currently I believe that this an error with snap building itself that it doesn't properly map it's olugins.

This is what the electron generated snapcraft.yml looks like:
```
name: superproductivity
version: 1.3.6
summary: superProductivity
description: Personal Task Management App to help you with your daily struggle with JIRA etc.
confinement: strict
grade: stable
icon: snap/gui/icon.png
apps:
  superproductivity:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/superproductivity
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    source: /home/user/www/super-productivity/dist/linux-unpacked
    after:
      - desktop-glib-only
```
