### ISSUE TITLE
💡 Add Environment variables or config file for WebDav Sync as default in settings

### ISSUE THREAD

**Issue by BaccanoMob** [johannesjo/super-productivity#4545]
### Problem Statement

I followed the Readme file to install super-productivity via docker compose with webdav support. It works great. 

The only problem is that I sometimes work in incognito and the data does not presist. To pull the data from webdav I need to re enter the creds which is fine but it is a few text/check boxes. Since I always type in the same values in the field, won't it be helpful if the values are taken from environment variables?

### Possible Solution

List of environment variables I suggest:

- WEBDAV_BASE_URL (defaults = "")
- WEBDAV_USER (defaults = "")
- WEBDAV_PASSWORD (Though I usually wont recommend, it might be useful for someone having a proxy auth like authelia, traefik, etc)(defaults = "")
- WEBDAV_SYNC_FOLDER (defaults = "super-productivity")
- WEBDAV_SYNC_INTERVAL(defaults = "1m")
- WEBDAV_ADV_COMPRESSION (defaults = "false")
- WEBDAV_ADV_E2E (defaults = "false")

Additional Info:
- Default for WEBDAV_BASE_URL can be <app_url>/webdav/ if WEBDAV_BACKEND is enabled

### Describe alternatives you've considered

Maybe load a config.yml like how webdav does with `webdav.yml`.

```yaml
... # with other settings if this becomes a thing
webdav:
  base_url: ""
  user: ""
  password: ""
  sync_folder: "super-productivity"
  advanced:
    compression: false
    e2e: false
```

Personally I like the config file approach since I don't like passwords as environment variable.

### Additional context

@kkoyung Just tagging you since you made pull requests #3534 #3688 and you may know more on this.

**Comment by thecoffeebin** [comment]
Hi @BaccanoMob 

I'm also just spinned up docker-compose on my server with the YAML provided (docker-compose.yml and webdav.yaml) with WEBDAV_BACKEND=http://webdav as the environment variable, but I struggled to get webdav to work. One thing I did differently is that my docker is sitting behind Nginx Proxy Manager (exposed to public) instead of running it as http://localhost.

Any help is greatly appreciated!

**Comment by BaccanoMob** [comment]
@thecoffeebin 

I also had the same struggles was getting some NotOkAPIError or something. These are the steps I did to make it working.

1. I modified to include networks and labels (this is according to traefik, but should be the same for NPM except the labels)

<details>
<summary>compose.yml
</summary>

```yaml
services:
  sp:
    image: johannesjo/super-productivity:latest
    container_name: sp
    restart: unless-stopped
    # ports:
    #   - 80:80
    environment:
      - WEBDAV_BACKEND=http://webdav # Needed in this case
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.super.entrypoints=https"
      - "traefik.http.routers.super.rule=Host(YOUR.DOMAIN.COM)"
      - "traefik.http.routers.super.tls.certresolver=CERTRESOLVER"

  webdav: # This is the same webdav in `http://webdav`, 
    image: hacdias/webdav:latest
    container_name: webdav
    restart: unless-stopped
    volumes:
      - ./webdav.yaml:/config.yml:ro
      - ./data:/data
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    internal: true
```

</details>

<details>
<summary>webdav.yml
</summary>

```yaml
address: 0.0.0.0
port: 80

prefix: /
permissions: CRUD

users:
  - username: user
    password: password # can be a hashed password, check hacdias/webdav github repo
    directory: /data/user # must be something /data, /data/<user>would be easier to manage for multi account
```

</details>

2. You should make super-productivity directory inside webdav beforehand for each users. Aka `mkdir -p ./data/<user>/super-productivity` (You prolly missed this). Also it is possible to use a different folder like `tasks` ( ./data/<user>/tasks)

3. Sync settings:
    - Base url = `https://YOUR.DOMAIN.COM/webdav/` (The trailing / is needed AFAIK and prolly missed this too)
    - sync folder = "tasks" (if you changed in previous point)
    - The other fields should be intuitive.

4. I did not turn on any of the Advanced config since there were some issues mentioned (like with E2E)

Hopefully it works for you!! (and helpful for others)
